export const PRODUCTS_ACTION_TYPES = {
    FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
    SET_CATEGORIES: 'GET_CATEGORIES',
    SET_PRODUCTSBYCATEGORY: 'GET_PRODUCTSBYCATEGORY',
    POST_PRODUCTS_START: 'POST_PRODUCTS_START',
    POST_PRODUCTS_SUCCESS: 'POST_PRODUCTS_SUCCESS',
    POST_PRODUCTS_FAILURE: 'POST_PRODUCTS_FAILURE',
}
