const SHOP_DATA =
  [
    {
      id: 1,
      title: 'Brown Brim',
      image: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
      price: 25,
      category: 'Hats',
    },
    {
      id: 2,
      title: 'Blue Beanie',
      image: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
      price: 18,
      category: 'Hats',
    },
    {
      id: 3,
      title: 'Brown Cowboy',
      image: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
      price: 35,
      category: 'Hats',
    },
    {
      id: 4,
      title: 'Grey Brim',
      image: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
      price: 25,
      category: 'Hats',
    },
    {
      id: 5,
      title: 'Green Beanie',
      image: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
      price: 18,
      category: 'Hats',
    },
    {
      id: 6,
      title: 'Palm Tree Cap',
      image: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
      price: 14,
      category: 'Hats',
    },
    {
      id: 7,
      title: 'Red Beanie',
      image: 'https://i.ibb.co/bLB646Z/red-beanie.png',
      price: 18,
      category: 'Hats',
    },
    {
      id: 8,
      title: 'Wolf Cap',
      image: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
      price: 14,
      category: 'Hats',
    },
    {
      id: 9,
      title: 'Blue Snapback',
      image: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
      price: 16,
      category: 'Hats',
    },
    {
      id: 10,
      title: 'Adidas NMD',
      image: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
      price: 220,
      category: 'Sneakers',
    },
    {
      id: 11,
      title: 'Adidas Yeezy',
      image: 'https://i.ibb.co/dJbG1cT/yeezy.png',
      price: 280,
      category: 'Sneakers',
    },
    {
      id: 12,
      title: 'Black Converse',
      image: 'https://i.ibb.co/bPmVXyP/black-converse.png',
      price: 110,
      category: 'Sneakers',
    },
    {
      id: 13,
      title: 'Nike White AirForce',
      image: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png',
      price: 160,
      category: 'Sneakers',
    },
    {
      id: 14,
      title: 'Nike Red High Tops',
      image: 'https://i.ibb.co/QcvzydB/nikes-red.png',
      price: 160,
      category: 'Sneakers',
    },
    {
      id: 15,
      title: 'Nike Brown High Tops',
      image: 'https://i.ibb.co/fMTV342/nike-brown.png',
      price: 160,
      category: 'Sneakers',
    },
    {
      id: 16,
      title: 'Air Jordan Limited',
      image: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
      price: 190,
      category: 'Sneakers',
    },
    {
      id: 17,
      title: 'Timberlands',
      image: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
      price: 200,
      category: 'Sneakers',
    },
    {
      id: 18,
      title: 'Black Jean Shearling',
      image: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
      price: 125,
      category: 'Jackets',
    },
    {
      id: 19,
      title: 'Blue Jean Jacket',
      image: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
      price: 90,
      category: 'Jackets',
    },
    {
      id: 20,
      title: 'Grey Jean Jacket',
      image: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
      price: 90,
      category: 'Jackets',
    },
    {
      id: 21,
      title: 'Brown Shearling',
      image: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
      price: 165,
      category: 'Jackets',
    },
    {
      id: 22,
      title: 'Tan Trench',
      image: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
      price: 185,
      category: 'Jackets',
    },
    {
      id: 23,
      title: 'Blue Tanktop',
      image: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
      price: 25,
      category: 'Womens',
    },
    {
      id: 24,
      title: 'Floral Blouse',
      image: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
      price: 20,
      category: 'Womens',
    },
    {
      id: 25,
      title: 'Floral Dress',
      image: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
      price: 80,
      category: 'Womens',
    },
    {
      id: 26,
      title: 'Red Dots Dress',
      image: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
      price: 80,
      category: 'Womens',
    },
    {
      id: 27,
      title: 'Striped Sweater',
      image: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
      price: 45,
      category: 'Womens',
    },
    {
      id: 28,
      title: 'Yellow Track Suit',
      image: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
      price: 135,
      category: 'Womens',
    },
    {
      id: 29,
      title: 'White Blouse',
      image: 'https://i.ibb.co/qBcrsJg/white-vest.png',
      price: 20,
      category: 'Womens',
    },
    {
      id: 30,
      title: 'Camo Down Vest',
      image: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
      price: 325,
      category: 'Mens',
    },
    {
      id: 31,
      title: 'Floral T-shirt',
      image: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
      price: 20,
      category: 'Mens',
    },
    {
      id: 32,
      title: 'Black & White Longsleeve',
      image: 'https://i.ibb.co/55z32tw/long-sleeve.png',
      price: 25,
      category: 'Mens',
    },
    {
      id: 33,
      title: 'Pink T-shirt',
      image: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
      price: 25,
      category: 'Mens',
    },
    {
      id: 34,
      title: 'Jean Long Sleeve',
      image: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
      price: 40,
      category: 'Mens',
    },
    {
      id: 35,
      title: 'Burgundy T-shirt',
      image: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
      price: 25,
      category: 'Mens',
    },
  ];

export default SHOP_DATA;